### ISSUE TITLE
Issues when hosted in webserver

### ISSUE THREAD

**Issue by rrightwrong** [PeculiarVentures/fortify-examples#4]
Hi ! I am facing the errors when the examples (Tested Example5) are hosted on webserver (IIS) and when  accessing examples through server IP. 

`Uncaught (in promise) DOMException: Failed to execute 'put' on 'IDBObjectStore': function SHA256()`
`webcrypto-socket.js:4403`

`AlgorithmError: Unrecognized name`
`example5.html:78`

However, it functions well for localhost.

**Comment by rmhrisk** [comment]
Is the site over HTTPS?

**Comment by rrightwrong** [comment]
No its HTTP.

**Comment by rmhrisk** [comment]
WebCrypto will not work without HTTPS.

Pick up an ACME client, get a certificate from Let's Encrypt.

**Comment by rmhrisk** [comment]
see https://www.chromium.org/blink/webcrypto and "Access to the WebCrypto API is restricted to secure origins (which is to say https:// pages)."

**Comment by rrightwrong** [comment]
Thanks Ryan !!!
